;
import * as route0 from "/assets/root-CFzupUj3.js";
import * as route1 from "/assets/ErrorBoundaryLayout-B_mD__81.js";
import * as route2 from "/assets/LoggedInLayout-Cy5LBSdo.js";
import * as route3 from "/assets/SkeletonLayout-6FAMC6DB.js";
import * as route4 from "/assets/ModelLikesLayout-tSiLYKEH.js";
import * as route5 from "/assets/SidebarNavMainLayout-BmbvPv8I.js";
import * as route6 from "/assets/ChatRootLayout-VAnmm_62.js";
import * as route7 from "/assets/ChatHistoryLayout-BZAuHqpk.js";
import * as route8 from "/assets/ErrorBoundaryLayout-B_mD__81.js";
import * as route9 from "/assets/ChatPage-CQYLHMt3.js";
  window.__reactRouterManifest = {
  "entry": {
    "module": "/assets/entry.client-C46D5MBi.js",
    "imports": [
      "/assets/chunk-CLHnkPwZ.js",
      "/assets/preload-helper-DvmWZm-X.js",
      "/assets/captureSentryError-u88tboso.js",
      "/assets/DetailedError-CTuHunha.js",
      "/assets/chunk-JPUPSTYD-BhKMshOC.js",
      "/assets/react-dom-Cz5EEOlY.js",
      "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
      "/assets/jsx-runtime-hVLyBpah.js",
      "/assets/react-BNW_8c6p.js"
    ],
    "css": []
  },
  "routes": {
    "root": {
      "id": "root",
      "path": "",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": true,
      "module": "/assets/root-CFzupUj3.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/OnboardingCoreProvider-Dm6pD5M0.js",
        "/assets/UserAvatar-96ov2dt8.js",
        "/assets/MainLayout-DAm8Jvd9.js",
        "/assets/Providers-CuMfZdUn.js",
        "/assets/useOptimisticNavigation-BWBFFSqn.js",
        "/assets/useTrackPageView-BjXqrR2W.js",
        "/assets/useFeatureFlag-V-EwuREs.js",
        "/assets/useRegisterNavigationBlocker-B_qyvCCX.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/ErrorBoundaryHandler-Cdk8N6dB.js",
        "/assets/generateMetaTitle-CYueRsYW.js",
        "/assets/useSignalValue-CSaNA4Hz.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/sidebar-8mYI97nm.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/switch-DRtKmdwj.js",
        "/assets/signals-core.module-CPyMEXzE.js",
        "/assets/select-HaMHzlOc.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/collapsible-B5e_Q6Ci.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-D-Xd3ui-.js",
        "/assets/dropdown-menu-RgOz4lCe.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/popover-PmZoysVh.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/dayjs.min-B5WD0s4i.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/esm-RBqfOx_R.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/card-D0CREluG.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/dialog-B6v7Mtgd.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/page-BIvHSfJl.js",
        "/assets/sheet-CKJW1pds.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/table-1G9iI0Oq.js",
        "/assets/use-breakpoint-C2bBdLJr.js",
        "/assets/use-max-width-and-height-breakpoint-e9WL3Fc5.js",
        "/assets/use-toast-DAfu3deW.js",
        "/assets/useLocalStorage-xsxzMu9-.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/api.client-DEob89QC.js",
        "/assets/api.types.generated-C7ahdu2l.js",
        "/assets/NexosImage-Cnd-vdWp.js",
        "/assets/RouterForm-DP3IKneI.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/ThemeContext-uIF-GX_j.js",
        "/assets/userSettings.intent-BK1iH4N7.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/useRouterForm-DzEbEfiF.js",
        "/assets/valibot-B2twkX1P.js",
        "/assets/QueryClientProvider-BC8kdgAV.js",
        "/assets/queryOptions-C9IJY6wk.js",
        "/assets/prop-types-C-N8eQIt.js",
        "/assets/message-CNc59a09.js",
        "/assets/dist-BuubZOra.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/utils-DlqJAScl.js",
        "/assets/useStoreState-Dol3NGV4.js",
        "/assets/useFetcherCallback-CN0rj-y3.js",
        "/assets/dist-pw__PIR8.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/user.utils-CRzJrtnp.js",
        "/assets/useRenderElement-wC90SmP3.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/ConfirmModalContext-DhHAPwcx.js",
        "/assets/EnvContext-C-lh3Y68.js",
        "/assets/GoBackContext-BBQQ_SDT.js",
        "/assets/useIntegrations-Kxyc9D_U.js",
        "/assets/IntercomContext-CuRO3fse.js",
        "/assets/OryContext-CQVBkl84.js",
        "/assets/chat-E0tuemcM.js",
        "/assets/chatCache.context-DqovenHs.js",
        "/assets/updateChat.mutation-lB-Ouy7H.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/isCompanyEnabled-uLZffINj.js",
        "/assets/CircularProgress-BEstchDv.js",
        "/assets/notifications.context-DrxLMS6-.js",
        "/assets/subscriptionStatus.utils-BtBAuoCD.js",
        "/assets/useBaseQuery-1IpycvGk.js",
        "/assets/infiniteQueryOptions-BOJSylZ0.js",
        "/assets/useMutation-B4zLwhzV.js",
        "/assets/mutationOptions-DRY1k9sw.js",
        "/assets/useQuery-BgeU90Hr.js",
        "/assets/compare-Br3z3FUS-DkXjARuU.js",
        "/assets/useSessionStorage-CprT7E2_.js",
        "/assets/PageHeader-6NIewl2M.js",
        "/assets/SidebarNav-CY7IwQnT.js",
        "/assets/TableSkeleton-PN8ijhsN.js",
        "/assets/userManagement.features-B_-XsrmE.js",
        "/assets/workflows.consts-BPXGSEeD.js",
        "/assets/array-B5LIMEws.js",
        "/assets/SidebarNavHeader-ajxrHivW.js",
        "/assets/hasPermission-CsYSx7if.js",
        "/assets/chat.features-CQ8s7goj.js",
        "/assets/useSuspenseQuery-B-RCmLv8.js",
        "/assets/curry-yVdJ4rDb.js",
        "/assets/dist-BEaCrTOs.js",
        "/assets/dist-Bn7i4I9Y.js",
        "/assets/dist-qVw4sBqw.js",
        "/assets/integrations.const-SfFd0FwI.js",
        "/assets/integrations.intent-LjuzAP1O.js",
        "/assets/api-DQn8vrsR.js",
        "/assets/api.types-CAiBaauy.js",
        "/assets/is-image-only-model-Dc9WLJ2h.js",
        "/assets/json-CGK88krZ.js",
        "/assets/object-BZMSzS04.js"
      ],
      "css": [
        "/assets/root-NigmN3CC.css#"
      ]
    },
    "routing/layouts/ErrorBoundaryLayout": {
      "id": "routing/layouts/ErrorBoundaryLayout",
      "parentId": "root",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": false,
      "hasErrorBoundary": true,
      "module": "/assets/ErrorBoundaryLayout-B_mD__81.js",
      "imports": [
        "/assets/ErrorBoundaryHandler-Cdk8N6dB.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/message-CNc59a09.js",
        "/assets/dist-BuubZOra.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/useIntl-BHxjy3vM.js"
      ],
      "css": []
    },
    "domains/auth/routes/LoggedInLayout": {
      "id": "domains/auth/routes/LoggedInLayout",
      "parentId": "routing/layouts/ErrorBoundaryLayout",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/LoggedInLayout-Cy5LBSdo.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/OnboardingCoreProvider-Dm6pD5M0.js",
        "/assets/NexosImage-Cnd-vdWp.js",
        "/assets/UserAvatar-96ov2dt8.js",
        "/assets/MainLayout-DAm8Jvd9.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/Providers-CuMfZdUn.js",
        "/assets/useOptimisticNavigation-BWBFFSqn.js",
        "/assets/useTrackPageView-BjXqrR2W.js",
        "/assets/useFeatureFlag-V-EwuREs.js",
        "/assets/SidebarNavHeader-ajxrHivW.js",
        "/assets/sidebar-8mYI97nm.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/switch-DRtKmdwj.js",
        "/assets/select-HaMHzlOc.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/collapsible-B5e_Q6Ci.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-D-Xd3ui-.js",
        "/assets/dropdown-menu-RgOz4lCe.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/popover-PmZoysVh.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/dayjs.min-B5WD0s4i.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/message-CNc59a09.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/esm-RBqfOx_R.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/card-D0CREluG.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/dialog-B6v7Mtgd.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/page-BIvHSfJl.js",
        "/assets/sheet-CKJW1pds.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/table-1G9iI0Oq.js",
        "/assets/use-breakpoint-C2bBdLJr.js",
        "/assets/use-max-width-and-height-breakpoint-e9WL3Fc5.js",
        "/assets/use-toast-DAfu3deW.js",
        "/assets/useLocalStorage-xsxzMu9-.js",
        "/assets/api.client-DEob89QC.js",
        "/assets/api.types.generated-C7ahdu2l.js",
        "/assets/RouterForm-DP3IKneI.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/ThemeContext-uIF-GX_j.js",
        "/assets/userSettings.intent-BK1iH4N7.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/useRouterForm-DzEbEfiF.js",
        "/assets/valibot-B2twkX1P.js",
        "/assets/QueryClientProvider-BC8kdgAV.js",
        "/assets/queryOptions-C9IJY6wk.js",
        "/assets/prop-types-C-N8eQIt.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/dist-BuubZOra.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/utils-DlqJAScl.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/useStoreState-Dol3NGV4.js",
        "/assets/useFetcherCallback-CN0rj-y3.js",
        "/assets/dist-pw__PIR8.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/user.utils-CRzJrtnp.js",
        "/assets/useRenderElement-wC90SmP3.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/ConfirmModalContext-DhHAPwcx.js",
        "/assets/EnvContext-C-lh3Y68.js",
        "/assets/GoBackContext-BBQQ_SDT.js",
        "/assets/useIntegrations-Kxyc9D_U.js",
        "/assets/IntercomContext-CuRO3fse.js",
        "/assets/OryContext-CQVBkl84.js",
        "/assets/chat-E0tuemcM.js",
        "/assets/chatCache.context-DqovenHs.js",
        "/assets/updateChat.mutation-lB-Ouy7H.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/isCompanyEnabled-uLZffINj.js",
        "/assets/CircularProgress-BEstchDv.js",
        "/assets/notifications.context-DrxLMS6-.js",
        "/assets/subscriptionStatus.utils-BtBAuoCD.js",
        "/assets/useBaseQuery-1IpycvGk.js",
        "/assets/infiniteQueryOptions-BOJSylZ0.js",
        "/assets/useMutation-B4zLwhzV.js",
        "/assets/mutationOptions-DRY1k9sw.js",
        "/assets/useQuery-BgeU90Hr.js",
        "/assets/compare-Br3z3FUS-DkXjARuU.js",
        "/assets/useSessionStorage-CprT7E2_.js",
        "/assets/PageHeader-6NIewl2M.js",
        "/assets/SidebarNav-CY7IwQnT.js",
        "/assets/TableSkeleton-PN8ijhsN.js",
        "/assets/userManagement.features-B_-XsrmE.js",
        "/assets/workflows.consts-BPXGSEeD.js",
        "/assets/array-B5LIMEws.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/hasPermission-CsYSx7if.js",
        "/assets/chat.features-CQ8s7goj.js",
        "/assets/useSuspenseQuery-B-RCmLv8.js",
        "/assets/curry-yVdJ4rDb.js",
        "/assets/dist-BEaCrTOs.js",
        "/assets/dist-Bn7i4I9Y.js",
        "/assets/dist-qVw4sBqw.js",
        "/assets/integrations.const-SfFd0FwI.js",
        "/assets/integrations.intent-LjuzAP1O.js",
        "/assets/api-DQn8vrsR.js",
        "/assets/api.types-CAiBaauy.js",
        "/assets/is-image-only-model-Dc9WLJ2h.js",
        "/assets/json-CGK88krZ.js",
        "/assets/signals-core.module-CPyMEXzE.js",
        "/assets/object-BZMSzS04.js"
      ],
      "css": []
    },
    "domains/shared/skeleton/routes/SkeletonLayout": {
      "id": "domains/shared/skeleton/routes/SkeletonLayout",
      "parentId": "domains/auth/routes/LoggedInLayout",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": true,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/SkeletonLayout-6FAMC6DB.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/OnboardingCoreProvider-Dm6pD5M0.js",
        "/assets/UserAvatar-96ov2dt8.js",
        "/assets/MainLayout-DAm8Jvd9.js",
        "/assets/useOptimisticNavigation-BWBFFSqn.js",
        "/assets/useFeatureFlag-V-EwuREs.js",
        "/assets/sidebar-8mYI97nm.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/switch-DRtKmdwj.js",
        "/assets/select-HaMHzlOc.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/collapsible-B5e_Q6Ci.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-D-Xd3ui-.js",
        "/assets/dropdown-menu-RgOz4lCe.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/popover-PmZoysVh.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/dayjs.min-B5WD0s4i.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/esm-RBqfOx_R.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/card-D0CREluG.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/dialog-B6v7Mtgd.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/page-BIvHSfJl.js",
        "/assets/sheet-CKJW1pds.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/table-1G9iI0Oq.js",
        "/assets/use-breakpoint-C2bBdLJr.js",
        "/assets/use-max-width-and-height-breakpoint-e9WL3Fc5.js",
        "/assets/useLocalStorage-xsxzMu9-.js",
        "/assets/api.client-DEob89QC.js",
        "/assets/api.types.generated-C7ahdu2l.js",
        "/assets/NexosImage-Cnd-vdWp.js",
        "/assets/RouterForm-DP3IKneI.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/ThemeContext-uIF-GX_j.js",
        "/assets/userSettings.intent-BK1iH4N7.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/useRouterForm-DzEbEfiF.js",
        "/assets/valibot-B2twkX1P.js",
        "/assets/QueryClientProvider-BC8kdgAV.js",
        "/assets/queryOptions-C9IJY6wk.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/prop-types-C-N8eQIt.js",
        "/assets/message-CNc59a09.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/dist-BuubZOra.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/utils-DlqJAScl.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/useStoreState-Dol3NGV4.js",
        "/assets/useFetcherCallback-CN0rj-y3.js",
        "/assets/dist-pw__PIR8.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/user.utils-CRzJrtnp.js",
        "/assets/useRenderElement-wC90SmP3.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/PageHeader-6NIewl2M.js",
        "/assets/isCompanyEnabled-uLZffINj.js",
        "/assets/SidebarNav-CY7IwQnT.js",
        "/assets/TableSkeleton-PN8ijhsN.js",
        "/assets/userManagement.features-B_-XsrmE.js",
        "/assets/workflows.consts-BPXGSEeD.js",
        "/assets/array-B5LIMEws.js",
        "/assets/SidebarNavHeader-ajxrHivW.js",
        "/assets/EnvContext-C-lh3Y68.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/CircularProgress-BEstchDv.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/hasPermission-CsYSx7if.js",
        "/assets/chat.features-CQ8s7goj.js",
        "/assets/useSuspenseQuery-B-RCmLv8.js",
        "/assets/useBaseQuery-1IpycvGk.js",
        "/assets/curry-yVdJ4rDb.js",
        "/assets/dist-BEaCrTOs.js",
        "/assets/dist-Bn7i4I9Y.js",
        "/assets/dist-qVw4sBqw.js"
      ],
      "css": []
    },
    "model-likes": {
      "id": "model-likes",
      "parentId": "domains/shared/skeleton/routes/SkeletonLayout",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/ModelLikesLayout-tSiLYKEH.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/preload-helper-DvmWZm-X.js"
      ],
      "css": []
    },
    "logged_in_sidebar_nav": {
      "id": "logged_in_sidebar_nav",
      "parentId": "model-likes",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/SidebarNavMainLayout-BmbvPv8I.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/api.client-DEob89QC.js",
        "/assets/OnboardingCoreProvider-Dm6pD5M0.js",
        "/assets/NexosImage-Cnd-vdWp.js",
        "/assets/RouterForm-DP3IKneI.js",
        "/assets/UserAvatar-96ov2dt8.js",
        "/assets/MainLayout-DAm8Jvd9.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/chat-E0tuemcM.js",
        "/assets/chat.schema-C8Ag5-F_.js",
        "/assets/updateChat.mutation-lB-Ouy7H.js",
        "/assets/useFeatureFlag-V-EwuREs.js",
        "/assets/SidebarNav-CY7IwQnT.js",
        "/assets/SidebarNavHeader-ajxrHivW.js",
        "/assets/SidebarNavCollapsible-BQ-IcOhX.js",
        "/assets/SidebarNavSpacer-D2GiEAdt.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/ReactQueryErrorBoundary-C0DOEdG3.js",
        "/assets/useRouterForm-DzEbEfiF.js",
        "/assets/sidebar-8mYI97nm.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/switch-DRtKmdwj.js",
        "/assets/select-HaMHzlOc.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/collapsible-B5e_Q6Ci.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-D-Xd3ui-.js",
        "/assets/dropdown-menu-RgOz4lCe.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/popover-PmZoysVh.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/useMutation-B4zLwhzV.js",
        "/assets/QueryClientProvider-BC8kdgAV.js",
        "/assets/useSuspenseInfiniteQuery-BAEZBNkj.js",
        "/assets/useSuspenseQuery-B-RCmLv8.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/dayjs.min-B5WD0s4i.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/react-error-boundary-Ck5rFbSc.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/dist-HUrbIReJ.js",
        "/assets/message-CNc59a09.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/client-only-CrvGfs_x.js",
        "/assets/esm-RBqfOx_R.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/card-D0CREluG.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/dialog-B6v7Mtgd.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/sheet-CKJW1pds.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/use-breakpoint-C2bBdLJr.js",
        "/assets/use-max-width-and-height-breakpoint-e9WL3Fc5.js",
        "/assets/use-toast-DAfu3deW.js",
        "/assets/useLocalStorage-xsxzMu9-.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/utils-DlqJAScl.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/api.types.generated-C7ahdu2l.js",
        "/assets/ThemeContext-uIF-GX_j.js",
        "/assets/userSettings.intent-BK1iH4N7.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/valibot-B2twkX1P.js",
        "/assets/queryOptions-C9IJY6wk.js",
        "/assets/prop-types-C-N8eQIt.js",
        "/assets/dist-BuubZOra.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/useStoreState-Dol3NGV4.js",
        "/assets/useFetcherCallback-CN0rj-y3.js",
        "/assets/dist-pw__PIR8.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/user.utils-CRzJrtnp.js",
        "/assets/useRenderElement-wC90SmP3.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/api.types-CAiBaauy.js",
        "/assets/is-image-only-model-Dc9WLJ2h.js",
        "/assets/json-CGK88krZ.js",
        "/assets/signals-core.module-CPyMEXzE.js",
        "/assets/infiniteQueryOptions-BOJSylZ0.js",
        "/assets/array-B5LIMEws.js",
        "/assets/useBaseQuery-1IpycvGk.js",
        "/assets/chat.const-CviFy4Xj.js",
        "/assets/nameValidation-BtYYLP2-.js",
        "/assets/mutationOptions-DRY1k9sw.js",
        "/assets/object-BZMSzS04.js",
        "/assets/EnvContext-C-lh3Y68.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/CircularProgress-BEstchDv.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/hasPermission-CsYSx7if.js",
        "/assets/chat.features-CQ8s7goj.js",
        "/assets/curry-yVdJ4rDb.js",
        "/assets/dist-BEaCrTOs.js",
        "/assets/dist-Bn7i4I9Y.js",
        "/assets/dist-qVw4sBqw.js",
        "/assets/infiniteQueryObserver-DpKLc_5U.js"
      ],
      "css": []
    },
    "domains/chat-exp/routes/ChatRootLayout": {
      "id": "domains/chat-exp/routes/ChatRootLayout",
      "parentId": "logged_in_sidebar_nav",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/ChatRootLayout-VAnmm_62.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/generateMetaTitle-CYueRsYW.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/preload-helper-DvmWZm-X.js"
      ],
      "css": []
    },
    "domains/chat-exp/routes/ChatHistoryLayout": {
      "id": "domains/chat-exp/routes/ChatHistoryLayout",
      "parentId": "domains/chat-exp/routes/ChatRootLayout",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/ChatHistoryLayout-BZAuHqpk.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/OnboardingCoreProvider-Dm6pD5M0.js",
        "/assets/UserAvatar-96ov2dt8.js",
        "/assets/MainLayout-DAm8Jvd9.js",
        "/assets/ModelLikeContext-Dn06a63V.js",
        "/assets/useOptimisticNavigation-BWBFFSqn.js",
        "/assets/chatLayout.context-C7glRG5S.js",
        "/assets/chat.const-CviFy4Xj.js",
        "/assets/useFeatureFlag-V-EwuREs.js",
        "/assets/sidebar-8mYI97nm.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/switch-DRtKmdwj.js",
        "/assets/select-HaMHzlOc.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/collapsible-B5e_Q6Ci.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-D-Xd3ui-.js",
        "/assets/dropdown-menu-RgOz4lCe.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/popover-PmZoysVh.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/useSuspenseQuery-B-RCmLv8.js",
        "/assets/dayjs.min-B5WD0s4i.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/esm-RBqfOx_R.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/card-D0CREluG.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/dialog-B6v7Mtgd.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/page-BIvHSfJl.js",
        "/assets/sheet-CKJW1pds.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/table-1G9iI0Oq.js",
        "/assets/use-breakpoint-C2bBdLJr.js",
        "/assets/use-max-width-and-height-breakpoint-e9WL3Fc5.js",
        "/assets/useLocalStorage-xsxzMu9-.js",
        "/assets/api.client-DEob89QC.js",
        "/assets/api.types.generated-C7ahdu2l.js",
        "/assets/NexosImage-Cnd-vdWp.js",
        "/assets/RouterForm-DP3IKneI.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/ThemeContext-uIF-GX_j.js",
        "/assets/userSettings.intent-BK1iH4N7.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/useRouterForm-DzEbEfiF.js",
        "/assets/valibot-B2twkX1P.js",
        "/assets/QueryClientProvider-BC8kdgAV.js",
        "/assets/queryOptions-C9IJY6wk.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/prop-types-C-N8eQIt.js",
        "/assets/message-CNc59a09.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/dist-BuubZOra.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/utils-DlqJAScl.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/useStoreState-Dol3NGV4.js",
        "/assets/useFetcherCallback-CN0rj-y3.js",
        "/assets/dist-pw__PIR8.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/user.utils-CRzJrtnp.js",
        "/assets/useRenderElement-wC90SmP3.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/array-B5LIMEws.js",
        "/assets/PageHeader-6NIewl2M.js",
        "/assets/isCompanyEnabled-uLZffINj.js",
        "/assets/SidebarNav-CY7IwQnT.js",
        "/assets/TableSkeleton-PN8ijhsN.js",
        "/assets/userManagement.features-B_-XsrmE.js",
        "/assets/workflows.consts-BPXGSEeD.js",
        "/assets/SidebarNavHeader-ajxrHivW.js",
        "/assets/EnvContext-C-lh3Y68.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/CircularProgress-BEstchDv.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/hasPermission-CsYSx7if.js",
        "/assets/chat.features-CQ8s7goj.js",
        "/assets/useBaseQuery-1IpycvGk.js",
        "/assets/curry-yVdJ4rDb.js",
        "/assets/dist-BEaCrTOs.js",
        "/assets/dist-Bn7i4I9Y.js",
        "/assets/dist-qVw4sBqw.js"
      ],
      "css": []
    },
    "error-boundary-chat-exp": {
      "id": "error-boundary-chat-exp",
      "parentId": "domains/chat-exp/routes/ChatHistoryLayout",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": false,
      "hasErrorBoundary": true,
      "module": "/assets/ErrorBoundaryLayout-B_mD__81.js",
      "imports": [
        "/assets/ErrorBoundaryHandler-Cdk8N6dB.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/message-CNc59a09.js",
        "/assets/dist-BuubZOra.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/useIntl-BHxjy3vM.js"
      ],
      "css": []
    },
    "chat-exp-chat-page": {
      "id": "chat-exp-chat-page",
      "parentId": "error-boundary-chat-exp",
      "path": "chat/:chatId?",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/ChatPage-CQYLHMt3.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/api.client-DEob89QC.js",
        "/assets/OnboardingCoreProvider-Dm6pD5M0.js",
        "/assets/ChangeModel-OuIJN-gC.js",
        "/assets/NexosImage-Cnd-vdWp.js",
        "/assets/ChatAssistantMessage-B4s_BUbz.js",
        "/assets/PageHeader-6NIewl2M.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/AudioContext-D7BhIael.js",
        "/assets/ModelLikeContext-Dn06a63V.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/chat-E0tuemcM.js",
        "/assets/chatLayout.context-C7glRG5S.js",
        "/assets/chat.const-CviFy4Xj.js",
        "/assets/chat.schema-C8Ag5-F_.js",
        "/assets/updateChat.mutation-lB-Ouy7H.js",
        "/assets/ChatToolbar-B2TP2AZM.js",
        "/assets/ChatPrompt-CpZSE7rG.js",
        "/assets/ChatConversationStarters-CfkC-SRM.js",
        "/assets/TemplateCard-BQ1WIjle.js",
        "/assets/useFeatureFlag-V-EwuREs.js",
        "/assets/notifications.context-DrxLMS6-.js",
        "/assets/SidebarNavHeader-ajxrHivW.js",
        "/assets/remarkInlineCitationToComponent-CPTzPRkR.js",
        "/assets/useSignalValue-CSaNA4Hz.js",
        "/assets/useDebounce-CC727KDh.js",
        "/assets/sidebar-8mYI97nm.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/switch-DRtKmdwj.js",
        "/assets/signals-core.module-CPyMEXzE.js",
        "/assets/select-HaMHzlOc.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/collapsible-B5e_Q6Ci.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-D-Xd3ui-.js",
        "/assets/dropdown-menu-RgOz4lCe.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/popover-PmZoysVh.js",
        "/assets/radio-group-Cg9UuOhn.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/QueryClientProvider-BC8kdgAV.js",
        "/assets/lib-Cp-VEzGJ.js",
        "/assets/chunk-RLXIAIE6-CPTQFGlo.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/dayjs.min-B5WD0s4i.js",
        "/assets/proxy-BT_8RZPY.js",
        "/assets/dist-BHUXpbkv.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/react-error-boundary-Ck5rFbSc.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/message-CNc59a09.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/dist-CK2JLpF0.js",
        "/assets/dist-BuubZOra.js",
        "/assets/esm-RBqfOx_R.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/alert-CoLDM0FC.js",
        "/assets/badge-DY17vp0C.js",
        "/assets/card-D0CREluG.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/chip-_v3IWCCg.js",
        "/assets/command-DLqEZses.js",
        "/assets/dialog-B6v7Mtgd.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/sheet-CKJW1pds.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/textarea-CnrRDWo3.js",
        "/assets/use-breakpoint-C2bBdLJr.js",
        "/assets/use-max-width-and-height-breakpoint-e9WL3Fc5.js",
        "/assets/use-toast-DAfu3deW.js",
        "/assets/useLocalStorage-xsxzMu9-.js",
        "/assets/usePreviousMemo-hMv0F_iT.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/utils-DlqJAScl.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/api.types.generated-C7ahdu2l.js",
        "/assets/RouterForm-DP3IKneI.js",
        "/assets/ThemeContext-uIF-GX_j.js",
        "/assets/userSettings.intent-BK1iH4N7.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/useRouterForm-DzEbEfiF.js",
        "/assets/valibot-B2twkX1P.js",
        "/assets/queryOptions-C9IJY6wk.js",
        "/assets/prop-types-C-N8eQIt.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/useStoreState-Dol3NGV4.js",
        "/assets/useFetcherCallback-CN0rj-y3.js",
        "/assets/dist-pw__PIR8.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/TrustedModelBadge-Bt9NqDhf.js",
        "/assets/useIntegrations-Kxyc9D_U.js",
        "/assets/IntegrationIcon-B25AGKg-.js",
        "/assets/useSharing-BacHGR-Q.js",
        "/assets/formatters-C-Viigg3.js",
        "/assets/is-image-only-model-Dc9WLJ2h.js",
        "/assets/dist-BMDdMia3.js",
        "/assets/array-B5LIMEws.js",
        "/assets/integrations.const-SfFd0FwI.js",
        "/assets/integrations.intent-LjuzAP1O.js",
        "/assets/dist-Bn7i4I9Y.js",
        "/assets/dist-qVw4sBqw.js",
        "/assets/dist-DIUFOOeN.js",
        "/assets/chatCache.context-DqovenHs.js",
        "/assets/completionStream.context-Dm-BDar3.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/userManagement.features-B_-XsrmE.js",
        "/assets/utils-D8mDw-1b.js",
        "/assets/formatters-BlBL_nHM.js",
        "/assets/json-CGK88krZ.js",
        "/assets/useAutoExpandReasoning-BdlpqRub.js",
        "/assets/useLastDefinedValue-BiNvAvUx.js",
        "/assets/dist-DqmgDH_m.js",
        "/assets/useSuspenseInfiniteQuery-BAEZBNkj.js",
        "/assets/AnimatePresence-zDqQJtI_.js",
        "/assets/object-BZMSzS04.js",
        "/assets/api.types-CAiBaauy.js",
        "/assets/infiniteQueryOptions-BOJSylZ0.js",
        "/assets/useBaseQuery-1IpycvGk.js",
        "/assets/nameValidation-BtYYLP2-.js",
        "/assets/piiEntityValues-BPCbDXi0.js",
        "/assets/curry-yVdJ4rDb.js",
        "/assets/dist-BEaCrTOs.js",
        "/assets/infiniteQueryObserver-DpKLc_5U.js",
        "/assets/useRenderElement-wC90SmP3.js",
        "/assets/mutationOptions-DRY1k9sw.js",
        "/assets/useConfirm-GBPk4LBM.js",
        "/assets/ConfirmModalContext-DhHAPwcx.js",
        "/assets/chat.features-CQ8s7goj.js",
        "/assets/IntegrationCredentialsDialog-BSTTp7pe.js",
        "/assets/InfoTooltip-D0n-hhY5.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/useFileDragNDrop-BcigRYwg.js",
        "/assets/floating-ui.react-B8NbYXEZ.js",
        "/assets/client-only-CrvGfs_x.js",
        "/assets/useQuery-BgeU90Hr.js",
        "/assets/compare-Br3z3FUS-DkXjARuU.js"
      ],
      "css": [
        "/assets/ChatAssistantMessage-BAMINjEF.css"
      ]
    },
    "index-chat-page": {
      "id": "index-chat-page",
      "parentId": "root",
      "index": true,
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": false,
      "hasErrorBoundary": false,
      "module": "/assets/ChatRedirectPage-CMY2pWcn.js",
      "imports": [],
      "css": []
    }
  },
  "url": "/assets/manifest-fb2652cc.js",
  "version": "fb2652cc"
};
  window.__reactRouterRouteModules = {"root":route0,"routing/layouts/ErrorBoundaryLayout":route1,"domains/auth/routes/LoggedInLayout":route2,"domains/shared/skeleton/routes/SkeletonLayout":route3,"model-likes":route4,"logged_in_sidebar_nav":route5,"domains/chat-exp/routes/ChatRootLayout":route6,"domains/chat-exp/routes/ChatHistoryLayout":route7,"error-boundary-chat-exp":route8,"chat-exp-chat-page":route9};

import("/assets/entry.client-C46D5MBi.js");