;
import * as route0 from "/assets/root-CFzupUj3.js";
import * as route1 from "/assets/ErrorBoundaryLayout-B_mD__81.js";
import * as route2 from "/assets/NoAuthLayout-akZW5UKq.js";
import * as route3 from "/assets/RegistrationEnabledLayout-CFFFghv8.js";
import * as route4 from "/assets/OryVerificationPage-BoANZfuM.js";
  window.__reactRouterManifest = {
  "entry": {
    "module": "/assets/entry.client-C46D5MBi.js",
    "imports": [
      "/assets/chunk-CLHnkPwZ.js",
      "/assets/preload-helper-DvmWZm-X.js",
      "/assets/captureSentryError-u88tboso.js",
      "/assets/DetailedError-CTuHunha.js",
      "/assets/chunk-JPUPSTYD-BhKMshOC.js",
      "/assets/react-dom-Cz5EEOlY.js",
      "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
      "/assets/jsx-runtime-hVLyBpah.js",
      "/assets/react-BNW_8c6p.js"
    ],
    "css": []
  },
  "routes": {
    "root": {
      "id": "root",
      "path": "",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": true,
      "module": "/assets/root-CFzupUj3.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/OnboardingCoreProvider-Dm6pD5M0.js",
        "/assets/UserAvatar-96ov2dt8.js",
        "/assets/MainLayout-DAm8Jvd9.js",
        "/assets/Providers-CuMfZdUn.js",
        "/assets/useOptimisticNavigation-BWBFFSqn.js",
        "/assets/useTrackPageView-BjXqrR2W.js",
        "/assets/useFeatureFlag-V-EwuREs.js",
        "/assets/useRegisterNavigationBlocker-B_qyvCCX.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/ErrorBoundaryHandler-Cdk8N6dB.js",
        "/assets/generateMetaTitle-CYueRsYW.js",
        "/assets/useSignalValue-CSaNA4Hz.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/sidebar-8mYI97nm.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/switch-DRtKmdwj.js",
        "/assets/signals-core.module-CPyMEXzE.js",
        "/assets/select-HaMHzlOc.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/collapsible-B5e_Q6Ci.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-D-Xd3ui-.js",
        "/assets/dropdown-menu-RgOz4lCe.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/popover-PmZoysVh.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/dayjs.min-B5WD0s4i.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/esm-RBqfOx_R.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/card-D0CREluG.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/dialog-B6v7Mtgd.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/page-BIvHSfJl.js",
        "/assets/sheet-CKJW1pds.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/table-1G9iI0Oq.js",
        "/assets/use-breakpoint-C2bBdLJr.js",
        "/assets/use-max-width-and-height-breakpoint-e9WL3Fc5.js",
        "/assets/use-toast-DAfu3deW.js",
        "/assets/useLocalStorage-xsxzMu9-.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/api.client-DEob89QC.js",
        "/assets/api.types.generated-C7ahdu2l.js",
        "/assets/NexosImage-Cnd-vdWp.js",
        "/assets/RouterForm-DP3IKneI.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/ThemeContext-uIF-GX_j.js",
        "/assets/userSettings.intent-BK1iH4N7.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/useRouterForm-DzEbEfiF.js",
        "/assets/valibot-B2twkX1P.js",
        "/assets/QueryClientProvider-BC8kdgAV.js",
        "/assets/queryOptions-C9IJY6wk.js",
        "/assets/prop-types-C-N8eQIt.js",
        "/assets/message-CNc59a09.js",
        "/assets/dist-BuubZOra.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/utils-DlqJAScl.js",
        "/assets/useStoreState-Dol3NGV4.js",
        "/assets/useFetcherCallback-CN0rj-y3.js",
        "/assets/dist-pw__PIR8.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/user.utils-CRzJrtnp.js",
        "/assets/useRenderElement-wC90SmP3.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/ConfirmModalContext-DhHAPwcx.js",
        "/assets/EnvContext-C-lh3Y68.js",
        "/assets/GoBackContext-BBQQ_SDT.js",
        "/assets/useIntegrations-Kxyc9D_U.js",
        "/assets/IntercomContext-CuRO3fse.js",
        "/assets/OryContext-CQVBkl84.js",
        "/assets/chat-E0tuemcM.js",
        "/assets/chatCache.context-DqovenHs.js",
        "/assets/updateChat.mutation-lB-Ouy7H.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/isCompanyEnabled-uLZffINj.js",
        "/assets/CircularProgress-BEstchDv.js",
        "/assets/notifications.context-DrxLMS6-.js",
        "/assets/subscriptionStatus.utils-BtBAuoCD.js",
        "/assets/useBaseQuery-1IpycvGk.js",
        "/assets/infiniteQueryOptions-BOJSylZ0.js",
        "/assets/useMutation-B4zLwhzV.js",
        "/assets/mutationOptions-DRY1k9sw.js",
        "/assets/useQuery-BgeU90Hr.js",
        "/assets/compare-Br3z3FUS-DkXjARuU.js",
        "/assets/useSessionStorage-CprT7E2_.js",
        "/assets/PageHeader-6NIewl2M.js",
        "/assets/SidebarNav-CY7IwQnT.js",
        "/assets/TableSkeleton-PN8ijhsN.js",
        "/assets/userManagement.features-B_-XsrmE.js",
        "/assets/workflows.consts-BPXGSEeD.js",
        "/assets/array-B5LIMEws.js",
        "/assets/SidebarNavHeader-ajxrHivW.js",
        "/assets/hasPermission-CsYSx7if.js",
        "/assets/chat.features-CQ8s7goj.js",
        "/assets/useSuspenseQuery-B-RCmLv8.js",
        "/assets/curry-yVdJ4rDb.js",
        "/assets/dist-BEaCrTOs.js",
        "/assets/dist-Bn7i4I9Y.js",
        "/assets/dist-qVw4sBqw.js",
        "/assets/integrations.const-SfFd0FwI.js",
        "/assets/integrations.intent-LjuzAP1O.js",
        "/assets/api-DQn8vrsR.js",
        "/assets/api.types-CAiBaauy.js",
        "/assets/is-image-only-model-Dc9WLJ2h.js",
        "/assets/json-CGK88krZ.js",
        "/assets/object-BZMSzS04.js"
      ],
      "css": [
        "/assets/root-NigmN3CC.css#"
      ]
    },
    "routing/layouts/ErrorBoundaryLayout": {
      "id": "routing/layouts/ErrorBoundaryLayout",
      "parentId": "root",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": false,
      "hasErrorBoundary": true,
      "module": "/assets/ErrorBoundaryLayout-B_mD__81.js",
      "imports": [
        "/assets/ErrorBoundaryHandler-Cdk8N6dB.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/UserContext-ulV3gBLg.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/mainLayout.context-Dlt8-mK5.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/message-CNc59a09.js",
        "/assets/dist-BuubZOra.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/useIntl-BHxjy3vM.js"
      ],
      "css": []
    },
    "no-auth-layout": {
      "id": "no-auth-layout",
      "parentId": "routing/layouts/ErrorBoundaryLayout",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/NoAuthLayout-akZW5UKq.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/IntercomContext-CuRO3fse.js",
        "/assets/useTrackPageView-BjXqrR2W.js",
        "/assets/lib-B6swq1_X.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/detectMobileDevice-kELObK7s.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/AnalyticsContext-CaymJjjY.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/dist-BuubZOra.js"
      ],
      "css": []
    },
    "registration-enabled-layout": {
      "id": "registration-enabled-layout",
      "parentId": "no-auth-layout",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/RegistrationEnabledLayout-CFFFghv8.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/preload-helper-DvmWZm-X.js"
      ],
      "css": []
    },
    "domains/auth/routes/ory/OryVerificationPage": {
      "id": "domains/auth/routes/ory/OryVerificationPage",
      "parentId": "registration-enabled-layout",
      "path": "authorization/verification",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/OryVerificationPage-BoANZfuM.js",
      "imports": [
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/OryContext-CQVBkl84.js",
        "/assets/useHandleFlowError-CNhA4pDE.js",
        "/assets/nodeOverrides.const-00X4uYxO.js",
        "/assets/Flow-CPW2wTi5.js",
        "/assets/OryFormWrapper-ymD-Lyit.js",
        "/assets/I18nProvider-Js801VN0.js",
        "/assets/typeguards-ClMzdHYA.js",
        "/assets/useEvent-Dofh-abJ.js",
        "/assets/dist-D2mA1oDw.js",
        "/assets/injectIntl-C1xce-tb.js",
        "/assets/api-DQn8vrsR.js",
        "/assets/checkbox-BRDien4_.js",
        "/assets/button-ChaV-wp4.js",
        "/assets/label-BdRB_5jF.js",
        "/assets/tooltip-CPmtT2gQ.js",
        "/assets/chunk-JPUPSTYD-BhKMshOC.js",
        "/assets/react-dom-Cz5EEOlY.js",
        "/assets/dist-CXMScWbG.js",
        "/assets/message-CNc59a09.js",
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/jsx-runtime-hVLyBpah.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/common-5Op7J-9H.js",
        "/assets/alert-CoLDM0FC.js",
        "/assets/input-DhdrBdDk.js",
        "/assets/form-BPiy-i1P.js",
        "/assets/skeleton-B2gNvyrI.js",
        "/assets/use-toast-DAfu3deW.js",
        "/assets/dist-BuubZOra.js",
        "/assets/useLogout-CoucZoAF.js",
        "/assets/useIntl-BHxjy3vM.js",
        "/assets/preload-helper-DvmWZm-X.js",
        "/assets/resolveMessage-B2LZ7_QE.js",
        "/assets/captureSentryError-u88tboso.js",
        "/assets/DetailedError-CTuHunha.js",
        "/assets/object-BZMSzS04.js",
        "/assets/dist-B6xdPpQ6.js",
        "/assets/utils-hQINeG7X.js",
        "/assets/dist-DdorpHs2.js",
        "/assets/bundle-mjs-C3x8Cmxv.js",
        "/assets/array-B5LIMEws.js"
      ],
      "css": []
    },
    "index-chat-page": {
      "id": "index-chat-page",
      "parentId": "root",
      "index": true,
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": false,
      "hasErrorBoundary": false,
      "module": "/assets/ChatRedirectPage-CMY2pWcn.js",
      "imports": [],
      "css": []
    },
    "routes/NotFound": {
      "id": "routes/NotFound",
      "parentId": "routing/layouts/ErrorBoundaryLayout",
      "path": "*",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/assets/NotFound-B3JrO1my.js",
      "imports": [
        "/assets/chunk-LFPYN7LY-DvFZTgRa.js",
        "/assets/react-BNW_8c6p.js",
        "/assets/chunk-CLHnkPwZ.js",
        "/assets/preload-helper-DvmWZm-X.js"
      ],
      "css": []
    }
  },
  "url": "/assets/manifest-fb2652cc.js",
  "version": "fb2652cc"
};
  window.__reactRouterRouteModules = {"root":route0,"routing/layouts/ErrorBoundaryLayout":route1,"no-auth-layout":route2,"registration-enabled-layout":route3,"domains/auth/routes/ory/OryVerificationPage":route4};

import("/assets/entry.client-C46D5MBi.js");